/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/MatchRoom.def
	public class EntityBaseEntityCall_MatchRoomBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityBaseEntityCall_MatchRoomBase(UInt16 ecpID, Int32 eid) : base(eid, "MatchRoom")
		{
			entityComponentPropertyID = ecpID;
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

	}

	public class EntityCellEntityCall_MatchRoomBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityCellEntityCall_MatchRoomBase(UInt16 ecpID, Int32 eid) : base(eid, "MatchRoom")
		{
			entityComponentPropertyID = ecpID;
			className = "MatchRoom";
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
