/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Chat.def
	public class EntityBaseEntityCall_ChatBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityBaseEntityCall_ChatBase(UInt16 ecpID, Int32 eid) : base(eid, "Chat")
		{
			entityComponentPropertyID = ecpID;
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

	}

	public class EntityCellEntityCall_ChatBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityCellEntityCall_ChatBase(UInt16 ecpID, Int32 eid) : base(eid, "Chat")
		{
			entityComponentPropertyID = ecpID;
			className = "Chat";
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void say(string arg1)
		{
			Bundle pBundle = newCall("say", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeUnicode(arg1);
			sendCall(null);
		}

	}
	}
