/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAccountModule = new ScriptModule("Account");
			EntityDef.moduledefs["Account"] = pAccountModule;
			EntityDef.idmoduledefs[1] = pAccountModule;

			Property pAccount_position = new Property();
			pAccount_position.name = "position";
			pAccount_position.properUtype = 40000;
			pAccount_position.properFlags = 4;
			pAccount_position.aliasID = 1;
			Vector3 Account_position_defval = new Vector3();
			pAccount_position.defaultVal = Account_position_defval;
			pAccountModule.propertys["position"] = pAccount_position; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_position.aliasID] = pAccount_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(position / 40000).");

			Property pAccount_direction = new Property();
			pAccount_direction.name = "direction";
			pAccount_direction.properUtype = 40001;
			pAccount_direction.properFlags = 4;
			pAccount_direction.aliasID = 2;
			Vector3 Account_direction_defval = new Vector3();
			pAccount_direction.defaultVal = Account_direction_defval;
			pAccountModule.propertys["direction"] = pAccount_direction; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_direction.aliasID] = pAccount_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(direction / 40001).");

			Property pAccount_spaceID = new Property();
			pAccount_spaceID.name = "spaceID";
			pAccount_spaceID.properUtype = 40002;
			pAccount_spaceID.properFlags = 16;
			pAccount_spaceID.aliasID = 3;
			UInt32 Account_spaceID_defval;
			UInt32.TryParse("", out Account_spaceID_defval);
			pAccount_spaceID.defaultVal = Account_spaceID_defval;
			pAccountModule.propertys["spaceID"] = pAccount_spaceID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_spaceID.aliasID] = pAccount_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(spaceID / 40002).");

			Property pAccount_lastSelCharacter = new Property();
			pAccount_lastSelCharacter.name = "lastSelCharacter";
			pAccount_lastSelCharacter.properUtype = 2;
			pAccount_lastSelCharacter.properFlags = 32;
			pAccount_lastSelCharacter.aliasID = 4;
			UInt64 Account_lastSelCharacter_defval;
			UInt64.TryParse("0", out Account_lastSelCharacter_defval);
			pAccount_lastSelCharacter.defaultVal = Account_lastSelCharacter_defval;
			pAccountModule.propertys["lastSelCharacter"] = pAccount_lastSelCharacter; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_lastSelCharacter.aliasID] = pAccount_lastSelCharacter;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(lastSelCharacter / 2).");

			pAccountModule.useMethodDescrAlias = true;
			ScriptModule pAvatarModule = new ScriptModule("Avatar");
			EntityDef.moduledefs["Avatar"] = pAvatarModule;
			EntityDef.idmoduledefs[2] = pAvatarModule;

			Property pAvatar_position = new Property();
			pAvatar_position.name = "position";
			pAvatar_position.properUtype = 40000;
			pAvatar_position.properFlags = 4;
			pAvatar_position.aliasID = 1;
			Vector3 Avatar_position_defval = new Vector3();
			pAvatar_position.defaultVal = Avatar_position_defval;
			pAvatarModule.propertys["position"] = pAvatar_position; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_position.aliasID] = pAvatar_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(position / 40000).");

			Property pAvatar_direction = new Property();
			pAvatar_direction.name = "direction";
			pAvatar_direction.properUtype = 40001;
			pAvatar_direction.properFlags = 4;
			pAvatar_direction.aliasID = 2;
			Vector3 Avatar_direction_defval = new Vector3();
			pAvatar_direction.defaultVal = Avatar_direction_defval;
			pAvatarModule.propertys["direction"] = pAvatar_direction; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_direction.aliasID] = pAvatar_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(direction / 40001).");

			Property pAvatar_spaceID = new Property();
			pAvatar_spaceID.name = "spaceID";
			pAvatar_spaceID.properUtype = 40002;
			pAvatar_spaceID.properFlags = 16;
			pAvatar_spaceID.aliasID = 3;
			UInt32 Avatar_spaceID_defval;
			UInt32.TryParse("", out Avatar_spaceID_defval);
			pAvatar_spaceID.defaultVal = Avatar_spaceID_defval;
			pAvatarModule.propertys["spaceID"] = pAvatar_spaceID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_spaceID.aliasID] = pAvatar_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(spaceID / 40002).");

			Property pAvatar_component1 = new Property();
			pAvatar_component1.name = "component1";
			pAvatar_component1.properUtype = 7;
			pAvatar_component1.properFlags = 157;
			pAvatar_component1.aliasID = 4;
			pAvatarModule.propertys["component1"] = pAvatar_component1; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_component1.aliasID] = pAvatar_component1;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(component1 / 7).");

			Property pAvatar_component2 = new Property();
			pAvatar_component2.name = "component2";
			pAvatar_component2.properUtype = 10;
			pAvatar_component2.properFlags = 157;
			pAvatar_component2.aliasID = 5;
			pAvatarModule.propertys["component2"] = pAvatar_component2; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_component2.aliasID] = pAvatar_component2;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(component2 / 10).");

			Property pAvatar_name = new Property();
			pAvatar_name.name = "name";
			pAvatar_name.properUtype = 4;
			pAvatar_name.properFlags = 4;
			pAvatar_name.aliasID = 6;
			string Avatar_name_defval = "";
			pAvatar_name.defaultVal = Avatar_name_defval;
			pAvatarModule.propertys["name"] = pAvatar_name; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_name.aliasID] = pAvatar_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(name / 4).");

			Property pAvatar_teamID = new Property();
			pAvatar_teamID.name = "teamID";
			pAvatar_teamID.properUtype = 6;
			pAvatar_teamID.properFlags = 4;
			pAvatar_teamID.aliasID = 7;
			SByte Avatar_teamID_defval;
			SByte.TryParse("0", out Avatar_teamID_defval);
			pAvatar_teamID.defaultVal = Avatar_teamID_defval;
			pAvatarModule.propertys["teamID"] = pAvatar_teamID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_teamID.aliasID] = pAvatar_teamID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(teamID / 6).");

			pAvatarModule.useMethodDescrAlias = true;
			ScriptModule pFrameSyncReportModule = new ScriptModule("FrameSyncReport");
			EntityDef.moduledefs["FrameSyncReport"] = pFrameSyncReportModule;
			EntityDef.idmoduledefs[3] = pFrameSyncReportModule;

			Property pFrameSyncReport_position = new Property();
			pFrameSyncReport_position.name = "position";
			pFrameSyncReport_position.properUtype = 40000;
			pFrameSyncReport_position.properFlags = 4;
			pFrameSyncReport_position.aliasID = 1;
			Vector3 FrameSyncReport_position_defval = new Vector3();
			pFrameSyncReport_position.defaultVal = FrameSyncReport_position_defval;
			pFrameSyncReportModule.propertys["position"] = pFrameSyncReport_position; 

			pFrameSyncReportModule.usePropertyDescrAlias = true;
			pFrameSyncReportModule.idpropertys[(UInt16)pFrameSyncReport_position.aliasID] = pFrameSyncReport_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(FrameSyncReport), property(position / 40000).");

			Property pFrameSyncReport_direction = new Property();
			pFrameSyncReport_direction.name = "direction";
			pFrameSyncReport_direction.properUtype = 40001;
			pFrameSyncReport_direction.properFlags = 4;
			pFrameSyncReport_direction.aliasID = 2;
			Vector3 FrameSyncReport_direction_defval = new Vector3();
			pFrameSyncReport_direction.defaultVal = FrameSyncReport_direction_defval;
			pFrameSyncReportModule.propertys["direction"] = pFrameSyncReport_direction; 

			pFrameSyncReportModule.usePropertyDescrAlias = true;
			pFrameSyncReportModule.idpropertys[(UInt16)pFrameSyncReport_direction.aliasID] = pFrameSyncReport_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(FrameSyncReport), property(direction / 40001).");

			Property pFrameSyncReport_spaceID = new Property();
			pFrameSyncReport_spaceID.name = "spaceID";
			pFrameSyncReport_spaceID.properUtype = 40002;
			pFrameSyncReport_spaceID.properFlags = 16;
			pFrameSyncReport_spaceID.aliasID = 3;
			UInt32 FrameSyncReport_spaceID_defval;
			UInt32.TryParse("", out FrameSyncReport_spaceID_defval);
			pFrameSyncReport_spaceID.defaultVal = FrameSyncReport_spaceID_defval;
			pFrameSyncReportModule.propertys["spaceID"] = pFrameSyncReport_spaceID; 

			pFrameSyncReportModule.usePropertyDescrAlias = true;
			pFrameSyncReportModule.idpropertys[(UInt16)pFrameSyncReport_spaceID.aliasID] = pFrameSyncReport_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(FrameSyncReport), property(spaceID / 40002).");

			Property pFrameSyncReport_seatNo = new Property();
			pFrameSyncReport_seatNo.name = "seatNo";
			pFrameSyncReport_seatNo.properUtype = 9;
			pFrameSyncReport_seatNo.properFlags = 16;
			pFrameSyncReport_seatNo.aliasID = 4;
			SByte FrameSyncReport_seatNo_defval;
			SByte.TryParse("0", out FrameSyncReport_seatNo_defval);
			pFrameSyncReport_seatNo.defaultVal = FrameSyncReport_seatNo_defval;
			pFrameSyncReportModule.propertys["seatNo"] = pFrameSyncReport_seatNo; 

			pFrameSyncReportModule.usePropertyDescrAlias = true;
			pFrameSyncReportModule.idpropertys[(UInt16)pFrameSyncReport_seatNo.aliasID] = pFrameSyncReport_seatNo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(FrameSyncReport), property(seatNo / 9).");

			List<DATATYPE_BASE> pFrameSyncReport_onFrameMessage_args = new List<DATATYPE_BASE>();
			pFrameSyncReport_onFrameMessage_args.Add(EntityDef.id2datatypes[27]);

			Method pFrameSyncReport_onFrameMessage = new Method();
			pFrameSyncReport_onFrameMessage.name = "onFrameMessage";
			pFrameSyncReport_onFrameMessage.methodUtype = 4;
			pFrameSyncReport_onFrameMessage.aliasID = 1;
			pFrameSyncReport_onFrameMessage.args = pFrameSyncReport_onFrameMessage_args;

			pFrameSyncReportModule.methods["onFrameMessage"] = pFrameSyncReport_onFrameMessage; 
			pFrameSyncReportModule.useMethodDescrAlias = true;
			pFrameSyncReportModule.idmethods[(UInt16)pFrameSyncReport_onFrameMessage.aliasID] = pFrameSyncReport_onFrameMessage;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(FrameSyncReport), method(onFrameMessage / 4).");

			List<DATATYPE_BASE> pFrameSyncReport_reportFrame_args = new List<DATATYPE_BASE>();
			pFrameSyncReport_reportFrame_args.Add(EntityDef.id2datatypes[26]);

			Method pFrameSyncReport_reportFrame = new Method();
			pFrameSyncReport_reportFrame.name = "reportFrame";
			pFrameSyncReport_reportFrame.methodUtype = 2;
			pFrameSyncReport_reportFrame.aliasID = -1;
			pFrameSyncReport_reportFrame.args = pFrameSyncReport_reportFrame_args;

			pFrameSyncReportModule.methods["reportFrame"] = pFrameSyncReport_reportFrame; 
			pFrameSyncReportModule.cell_methods["reportFrame"] = pFrameSyncReport_reportFrame;

			pFrameSyncReportModule.idcell_methods[pFrameSyncReport_reportFrame.methodUtype] = pFrameSyncReport_reportFrame;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(FrameSyncReport), method(reportFrame / 2).");

			ScriptModule pOperationModule = new ScriptModule("Operation");
			EntityDef.moduledefs["Operation"] = pOperationModule;
			EntityDef.idmoduledefs[4] = pOperationModule;

			Property pOperation_position = new Property();
			pOperation_position.name = "position";
			pOperation_position.properUtype = 40000;
			pOperation_position.properFlags = 4;
			pOperation_position.aliasID = 1;
			Vector3 Operation_position_defval = new Vector3();
			pOperation_position.defaultVal = Operation_position_defval;
			pOperationModule.propertys["position"] = pOperation_position; 

			pOperationModule.usePropertyDescrAlias = true;
			pOperationModule.idpropertys[(UInt16)pOperation_position.aliasID] = pOperation_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), property(position / 40000).");

			Property pOperation_direction = new Property();
			pOperation_direction.name = "direction";
			pOperation_direction.properUtype = 40001;
			pOperation_direction.properFlags = 4;
			pOperation_direction.aliasID = 2;
			Vector3 Operation_direction_defval = new Vector3();
			pOperation_direction.defaultVal = Operation_direction_defval;
			pOperationModule.propertys["direction"] = pOperation_direction; 

			pOperationModule.usePropertyDescrAlias = true;
			pOperationModule.idpropertys[(UInt16)pOperation_direction.aliasID] = pOperation_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), property(direction / 40001).");

			Property pOperation_spaceID = new Property();
			pOperation_spaceID.name = "spaceID";
			pOperation_spaceID.properUtype = 40002;
			pOperation_spaceID.properFlags = 16;
			pOperation_spaceID.aliasID = 3;
			UInt32 Operation_spaceID_defval;
			UInt32.TryParse("", out Operation_spaceID_defval);
			pOperation_spaceID.defaultVal = Operation_spaceID_defval;
			pOperationModule.propertys["spaceID"] = pOperation_spaceID; 

			pOperationModule.usePropertyDescrAlias = true;
			pOperationModule.idpropertys[(UInt16)pOperation_spaceID.aliasID] = pOperation_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), property(spaceID / 40002).");

			List<DATATYPE_BASE> pOperation_readyResult_args = new List<DATATYPE_BASE>();
			pOperation_readyResult_args.Add(EntityDef.id2datatypes[2]);

			Method pOperation_readyResult = new Method();
			pOperation_readyResult.name = "readyResult";
			pOperation_readyResult.methodUtype = 14;
			pOperation_readyResult.aliasID = 1;
			pOperation_readyResult.args = pOperation_readyResult_args;

			pOperationModule.methods["readyResult"] = pOperation_readyResult; 
			pOperationModule.useMethodDescrAlias = true;
			pOperationModule.idmethods[(UInt16)pOperation_readyResult.aliasID] = pOperation_readyResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(readyResult / 14).");

			List<DATATYPE_BASE> pOperation_rspHeroInfo_args = new List<DATATYPE_BASE>();
			pOperation_rspHeroInfo_args.Add(EntityDef.id2datatypes[35]);

			Method pOperation_rspHeroInfo = new Method();
			pOperation_rspHeroInfo.name = "rspHeroInfo";
			pOperation_rspHeroInfo.methodUtype = 16;
			pOperation_rspHeroInfo.aliasID = 2;
			pOperation_rspHeroInfo.args = pOperation_rspHeroInfo_args;

			pOperationModule.methods["rspHeroInfo"] = pOperation_rspHeroInfo; 
			pOperationModule.useMethodDescrAlias = true;
			pOperationModule.idmethods[(UInt16)pOperation_rspHeroInfo.aliasID] = pOperation_rspHeroInfo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(rspHeroInfo / 16).");

			List<DATATYPE_BASE> pOperation_rspPropsInfo_args = new List<DATATYPE_BASE>();
			pOperation_rspPropsInfo_args.Add(EntityDef.id2datatypes[38]);

			Method pOperation_rspPropsInfo = new Method();
			pOperation_rspPropsInfo.name = "rspPropsInfo";
			pOperation_rspPropsInfo.methodUtype = 17;
			pOperation_rspPropsInfo.aliasID = 3;
			pOperation_rspPropsInfo.args = pOperation_rspPropsInfo_args;

			pOperationModule.methods["rspPropsInfo"] = pOperation_rspPropsInfo; 
			pOperationModule.useMethodDescrAlias = true;
			pOperationModule.idmethods[(UInt16)pOperation_rspPropsInfo.aliasID] = pOperation_rspPropsInfo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(rspPropsInfo / 17).");

			List<DATATYPE_BASE> pOperation_rspRoadInfo_args = new List<DATATYPE_BASE>();
			pOperation_rspRoadInfo_args.Add(EntityDef.id2datatypes[32]);

			Method pOperation_rspRoadInfo = new Method();
			pOperation_rspRoadInfo.name = "rspRoadInfo";
			pOperation_rspRoadInfo.methodUtype = 15;
			pOperation_rspRoadInfo.aliasID = 4;
			pOperation_rspRoadInfo.args = pOperation_rspRoadInfo_args;

			pOperationModule.methods["rspRoadInfo"] = pOperation_rspRoadInfo; 
			pOperationModule.useMethodDescrAlias = true;
			pOperationModule.idmethods[(UInt16)pOperation_rspRoadInfo.aliasID] = pOperation_rspRoadInfo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(rspRoadInfo / 15).");

			List<DATATYPE_BASE> pOperation_rspShopInfo_args = new List<DATATYPE_BASE>();
			pOperation_rspShopInfo_args.Add(EntityDef.id2datatypes[41]);

			Method pOperation_rspShopInfo = new Method();
			pOperation_rspShopInfo.name = "rspShopInfo";
			pOperation_rspShopInfo.methodUtype = 18;
			pOperation_rspShopInfo.aliasID = 5;
			pOperation_rspShopInfo.args = pOperation_rspShopInfo_args;

			pOperationModule.methods["rspShopInfo"] = pOperation_rspShopInfo; 
			pOperationModule.useMethodDescrAlias = true;
			pOperationModule.idmethods[(UInt16)pOperation_rspShopInfo.aliasID] = pOperation_rspShopInfo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(rspShopInfo / 18).");

			List<DATATYPE_BASE> pOperation_rspSkillInfo_args = new List<DATATYPE_BASE>();
			pOperation_rspSkillInfo_args.Add(EntityDef.id2datatypes[44]);

			Method pOperation_rspSkillInfo = new Method();
			pOperation_rspSkillInfo.name = "rspSkillInfo";
			pOperation_rspSkillInfo.methodUtype = 19;
			pOperation_rspSkillInfo.aliasID = 6;
			pOperation_rspSkillInfo.args = pOperation_rspSkillInfo_args;

			pOperationModule.methods["rspSkillInfo"] = pOperation_rspSkillInfo; 
			pOperationModule.useMethodDescrAlias = true;
			pOperationModule.idmethods[(UInt16)pOperation_rspSkillInfo.aliasID] = pOperation_rspSkillInfo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(rspSkillInfo / 19).");

			List<DATATYPE_BASE> pOperation_rspTeamInfo_args = new List<DATATYPE_BASE>();
			pOperation_rspTeamInfo_args.Add(EntityDef.id2datatypes[47]);

			Method pOperation_rspTeamInfo = new Method();
			pOperation_rspTeamInfo.name = "rspTeamInfo";
			pOperation_rspTeamInfo.methodUtype = 20;
			pOperation_rspTeamInfo.aliasID = 7;
			pOperation_rspTeamInfo.args = pOperation_rspTeamInfo_args;

			pOperationModule.methods["rspTeamInfo"] = pOperation_rspTeamInfo; 
			pOperationModule.useMethodDescrAlias = true;
			pOperationModule.idmethods[(UInt16)pOperation_rspTeamInfo.aliasID] = pOperation_rspTeamInfo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(rspTeamInfo / 20).");

			List<DATATYPE_BASE> pOperation_reqGamePause_args = new List<DATATYPE_BASE>();

			Method pOperation_reqGamePause = new Method();
			pOperation_reqGamePause.name = "reqGamePause";
			pOperation_reqGamePause.methodUtype = 6;
			pOperation_reqGamePause.aliasID = -1;
			pOperation_reqGamePause.args = pOperation_reqGamePause_args;

			pOperationModule.methods["reqGamePause"] = pOperation_reqGamePause; 
			pOperationModule.cell_methods["reqGamePause"] = pOperation_reqGamePause;

			pOperationModule.idcell_methods[pOperation_reqGamePause.methodUtype] = pOperation_reqGamePause;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqGamePause / 6).");

			List<DATATYPE_BASE> pOperation_reqGameRunning_args = new List<DATATYPE_BASE>();

			Method pOperation_reqGameRunning = new Method();
			pOperation_reqGameRunning.name = "reqGameRunning";
			pOperation_reqGameRunning.methodUtype = 7;
			pOperation_reqGameRunning.aliasID = -1;
			pOperation_reqGameRunning.args = pOperation_reqGameRunning_args;

			pOperationModule.methods["reqGameRunning"] = pOperation_reqGameRunning; 
			pOperationModule.cell_methods["reqGameRunning"] = pOperation_reqGameRunning;

			pOperationModule.idcell_methods[pOperation_reqGameRunning.methodUtype] = pOperation_reqGameRunning;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqGameRunning / 7).");

			List<DATATYPE_BASE> pOperation_reqHeroConf_args = new List<DATATYPE_BASE>();

			Method pOperation_reqHeroConf = new Method();
			pOperation_reqHeroConf.name = "reqHeroConf";
			pOperation_reqHeroConf.methodUtype = 8;
			pOperation_reqHeroConf.aliasID = -1;
			pOperation_reqHeroConf.args = pOperation_reqHeroConf_args;

			pOperationModule.methods["reqHeroConf"] = pOperation_reqHeroConf; 
			pOperationModule.cell_methods["reqHeroConf"] = pOperation_reqHeroConf;

			pOperationModule.idcell_methods[pOperation_reqHeroConf.methodUtype] = pOperation_reqHeroConf;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqHeroConf / 8).");

			List<DATATYPE_BASE> pOperation_reqPropsConf_args = new List<DATATYPE_BASE>();

			Method pOperation_reqPropsConf = new Method();
			pOperation_reqPropsConf.name = "reqPropsConf";
			pOperation_reqPropsConf.methodUtype = 9;
			pOperation_reqPropsConf.aliasID = -1;
			pOperation_reqPropsConf.args = pOperation_reqPropsConf_args;

			pOperationModule.methods["reqPropsConf"] = pOperation_reqPropsConf; 
			pOperationModule.cell_methods["reqPropsConf"] = pOperation_reqPropsConf;

			pOperationModule.idcell_methods[pOperation_reqPropsConf.methodUtype] = pOperation_reqPropsConf;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqPropsConf / 9).");

			List<DATATYPE_BASE> pOperation_reqReady_args = new List<DATATYPE_BASE>();
			pOperation_reqReady_args.Add(EntityDef.id2datatypes[2]);

			Method pOperation_reqReady = new Method();
			pOperation_reqReady.name = "reqReady";
			pOperation_reqReady.methodUtype = 5;
			pOperation_reqReady.aliasID = -1;
			pOperation_reqReady.args = pOperation_reqReady_args;

			pOperationModule.methods["reqReady"] = pOperation_reqReady; 
			pOperationModule.cell_methods["reqReady"] = pOperation_reqReady;

			pOperationModule.idcell_methods[pOperation_reqReady.methodUtype] = pOperation_reqReady;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqReady / 5).");

			List<DATATYPE_BASE> pOperation_reqRoadConf_args = new List<DATATYPE_BASE>();

			Method pOperation_reqRoadConf = new Method();
			pOperation_reqRoadConf.name = "reqRoadConf";
			pOperation_reqRoadConf.methodUtype = 10;
			pOperation_reqRoadConf.aliasID = -1;
			pOperation_reqRoadConf.args = pOperation_reqRoadConf_args;

			pOperationModule.methods["reqRoadConf"] = pOperation_reqRoadConf; 
			pOperationModule.cell_methods["reqRoadConf"] = pOperation_reqRoadConf;

			pOperationModule.idcell_methods[pOperation_reqRoadConf.methodUtype] = pOperation_reqRoadConf;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqRoadConf / 10).");

			List<DATATYPE_BASE> pOperation_reqShopConf_args = new List<DATATYPE_BASE>();

			Method pOperation_reqShopConf = new Method();
			pOperation_reqShopConf.name = "reqShopConf";
			pOperation_reqShopConf.methodUtype = 11;
			pOperation_reqShopConf.aliasID = -1;
			pOperation_reqShopConf.args = pOperation_reqShopConf_args;

			pOperationModule.methods["reqShopConf"] = pOperation_reqShopConf; 
			pOperationModule.cell_methods["reqShopConf"] = pOperation_reqShopConf;

			pOperationModule.idcell_methods[pOperation_reqShopConf.methodUtype] = pOperation_reqShopConf;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqShopConf / 11).");

			List<DATATYPE_BASE> pOperation_reqSkillConf_args = new List<DATATYPE_BASE>();

			Method pOperation_reqSkillConf = new Method();
			pOperation_reqSkillConf.name = "reqSkillConf";
			pOperation_reqSkillConf.methodUtype = 12;
			pOperation_reqSkillConf.aliasID = -1;
			pOperation_reqSkillConf.args = pOperation_reqSkillConf_args;

			pOperationModule.methods["reqSkillConf"] = pOperation_reqSkillConf; 
			pOperationModule.cell_methods["reqSkillConf"] = pOperation_reqSkillConf;

			pOperationModule.idcell_methods[pOperation_reqSkillConf.methodUtype] = pOperation_reqSkillConf;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqSkillConf / 12).");

			List<DATATYPE_BASE> pOperation_reqTeamConf_args = new List<DATATYPE_BASE>();

			Method pOperation_reqTeamConf = new Method();
			pOperation_reqTeamConf.name = "reqTeamConf";
			pOperation_reqTeamConf.methodUtype = 13;
			pOperation_reqTeamConf.aliasID = -1;
			pOperation_reqTeamConf.args = pOperation_reqTeamConf_args;

			pOperationModule.methods["reqTeamConf"] = pOperation_reqTeamConf; 
			pOperationModule.cell_methods["reqTeamConf"] = pOperation_reqTeamConf;

			pOperationModule.idcell_methods[pOperation_reqTeamConf.methodUtype] = pOperation_reqTeamConf;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqTeamConf / 13).");

		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "CMD_TYPE";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "SPACE_KEY";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "FRAMEID";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "INT8";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "ENTITY_ID";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "UID1";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 20;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "DIRECTION3D";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "AVATAR_DATA";
				DATATYPE_AVATAR_DATA datatype = new DATATYPE_AVATAR_DATA();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 23;
				string typeName = "AVATAR_INFOS";
				DATATYPE_AVATAR_INFOS datatype = new DATATYPE_AVATAR_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 24;
				string typeName = "AVATAR_INFOS_LIST";
				DATATYPE_AVATAR_INFOS_LIST datatype = new DATATYPE_AVATAR_INFOS_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 26;
				string typeName = "FS_ENTITY_DATA";
				DATATYPE_FS_ENTITY_DATA datatype = new DATATYPE_FS_ENTITY_DATA();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 27;
				string typeName = "FS_FRAME_DATA";
				DATATYPE_FS_FRAME_DATA datatype = new DATATYPE_FS_FRAME_DATA();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 29;
				string typeName = "FS_FRAME_LIST";
				DATATYPE_FS_FRAME_LIST datatype = new DATATYPE_FS_FRAME_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 31;
				string typeName = "D_ROAD_INFOS";
				DATATYPE_D_ROAD_INFOS datatype = new DATATYPE_D_ROAD_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 32;
				string typeName = "D_ROAD_INFOS_LIST";
				DATATYPE_D_ROAD_INFOS_LIST datatype = new DATATYPE_D_ROAD_INFOS_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 34;
				string typeName = "D_HERO_INFOS";
				DATATYPE_D_HERO_INFOS datatype = new DATATYPE_D_HERO_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 35;
				string typeName = "D_HERO_INFOS_LIST";
				DATATYPE_D_HERO_INFOS_LIST datatype = new DATATYPE_D_HERO_INFOS_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 37;
				string typeName = "D_PROPS_INFOS";
				DATATYPE_D_PROPS_INFOS datatype = new DATATYPE_D_PROPS_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 38;
				string typeName = "D_PROPS_INFOS_LIST";
				DATATYPE_D_PROPS_INFOS_LIST datatype = new DATATYPE_D_PROPS_INFOS_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 40;
				string typeName = "D_SHOP_INFOS";
				DATATYPE_D_SHOP_INFOS datatype = new DATATYPE_D_SHOP_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 41;
				string typeName = "D_SHOP_INFOS_LIST";
				DATATYPE_D_SHOP_INFOS_LIST datatype = new DATATYPE_D_SHOP_INFOS_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 43;
				string typeName = "D_SKILL_INFOS";
				DATATYPE_D_SKILL_INFOS datatype = new DATATYPE_D_SKILL_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 44;
				string typeName = "D_SKILL_INFOS_LIST";
				DATATYPE_D_SKILL_INFOS_LIST datatype = new DATATYPE_D_SKILL_INFOS_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 46;
				string typeName = "D_TEAM_INFOS";
				DATATYPE_D_TEAM_INFOS datatype = new DATATYPE_D_TEAM_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 47;
				string typeName = "D_TEAM_INFOS_LIST";
				DATATYPE_D_TEAM_INFOS_LIST datatype = new DATATYPE_D_TEAM_INFOS_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 49;
				string typeName = "AnonymousArray_49";
				string name = "ENTITY_COMPONENT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 50;
				string typeName = "AnonymousArray_50";
				string name = "ENTITY_COMPONENT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 51;
				string typeName = "AnonymousArray_51";
				string name = "ENTITY_COMPONENT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}