/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/MatchAvatar.def
	public class EntityBaseEntityCall_MatchAvatarBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityBaseEntityCall_MatchAvatarBase(UInt16 ecpID, Int32 eid) : base(eid, "MatchAvatar")
		{
			entityComponentPropertyID = ecpID;
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void reqExitMatch()
		{
			Bundle pBundle = newCall("reqExitMatch", entityComponentPropertyID);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqJoinMatch(D_MATCH_REQUEST arg1)
		{
			Bundle pBundle = newCall("reqJoinMatch", entityComponentPropertyID);
			if(pBundle == null)
				return;

			((DATATYPE_D_MATCH_REQUEST)EntityDef.id2datatypes[24]).addToStreamEx(bundle, arg1);
			sendCall(null);
		}

	}

	public class EntityCellEntityCall_MatchAvatarBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityCellEntityCall_MatchAvatarBase(UInt16 ecpID, Int32 eid) : base(eid, "MatchAvatar")
		{
			entityComponentPropertyID = ecpID;
			className = "MatchAvatar";
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
